import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/lg/supabase";

export const Route = createFileRoute("/admin/invite")({ ssr:false, component: AdminInvitePage });

function AdminInvitePage(){
  const navigate=useNavigate();
  const [ready,setReady]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false),[accepted,setAccepted]=useState(false);
  useEffect(()=>{void (async()=>{const {data,error}=await supabase.auth.getSession();if(error||!data.session){setError("This invitation is no longer active. Please open the latest invitation email.");return}setEmail(data.session.user.email||"");setReady(true)})()},[]);
  const complete=async()=>{setError("");if(password.length<8){setError("Use at least 8 characters.");return}if(password!==confirm){setError("Passwords do not match.");return}setSaving(true);try{const {error:updateError}=await supabase.auth.updateUser({password});if(updateError)throw updateError;const {error:acceptError}=await supabase.rpc("platform_accept_admin_invitation");if(acceptError)throw acceptError;setAccepted(true);window.setTimeout(()=>navigate({to:"/admin"}),700)}catch(e){setError(e instanceof Error?e.message:"Unable to complete invitation.")}finally{setSaving(false)}};
  if(accepted)return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",fontFamily:"Poppins,system-ui,sans-serif",background:"#f5f7fb"}}><section style={{background:"#fff",padding:30,borderRadius:22,maxWidth:520,textAlign:"center"}}><div style={{fontSize:42}}>✓</div><h1>Admin access activated</h1><p style={{color:"#64748b"}}>Your institute administrator workspace is ready. Opening the Admin Panel…</p></section></main>;
  return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",padding:20,fontFamily:"Poppins,system-ui,sans-serif",background:"linear-gradient(135deg,#f5f7fb,#eef2ff)"}}><section style={{width:"min(460px,100%)",background:"rgba(255,255,255,.9)",border:"1px solid #e2e8f0",borderRadius:24,padding:28,boxShadow:"0 20px 70px rgba(30,41,59,.12)"}}><div style={{fontSize:11,fontWeight:900,letterSpacing:1.5,color:"#4f46e5"}}>MAHIN · ADMIN ONBOARDING</div><h1 style={{margin:"8px 0"}}>Complete your invitation</h1><p style={{color:"#64748b"}}>{ready ? "Invitation for "+email : "Checking your secure invitation…"}</p><label style={{display:"block",fontSize:12,fontWeight:800,marginTop:18}}>New password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} disabled={!ready} style={{width:"100%",boxSizing:"border-box",padding:12,borderRadius:10,border:"1px solid #d8dee9",marginTop:6}}/></label><label style={{display:"block",fontSize:12,fontWeight:800,marginTop:12}}>Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} disabled={!ready} style={{width:"100%",boxSizing:"border-box",padding:12,borderRadius:10,border:"1px solid #d8dee9",marginTop:6}}/></label>{error&&<div role="alert" style={{marginTop:12,padding:11,borderRadius:10,background:"#fff1f2",color:"#b42318"}}>{error}</div>}<button type="button" disabled={!ready||saving} onClick={()=>void complete()} style={{width:"100%",border:0,borderRadius:11,padding:13,marginTop:18,background:"#4f46e5",color:"#fff",fontWeight:900,cursor:"pointer"}}>{saving?"Activating…":"Activate Admin Access"}</button></section></main>;
}