import type { ReactNode } from "react";
import { C } from "@/lg/data";
import ChangePassword from "@/lg/ChangePassword";

export type AdminPageKey="dashboard"|"students"|"teachers"|"batches"|"attendance"|"homework"|"examschedule"|"materials"|"announcements"|"accounts"|"search";
type Props={activePage:AdminPageKey;onNavigate:(page:AdminPageKey)=>void;onLogout:()=>void;title:string;subtitle?:string;children:ReactNode};

const NAV:Array<{key:AdminPageKey;icon:string;label:string}>=
[{key:"dashboard",icon:"🏠",label:"Dashboard"},{key:"students",icon:"🎓",label:"Students"},{key:"teachers",icon:"👨‍🏫",label:"Teachers"},{key:"batches",icon:"👥",label:"Batches"},{key:"attendance",icon:"✅",label:"Attendance"},{key:"homework",icon:"📝",label:"Homework"},{key:"examschedule",icon:"📋",label:"Exams"},{key:"materials",icon:"📚",label:"Materials"},{key:"announcements",icon:"📢",label:"News"},{key:"accounts",icon:"🔐",label:"Accounts"},{key:"search",icon:"🔍",label:"Search"}];

const ADMIN_CSS=`*{box-sizing:border-box}.admin-shell{display:flex;min-height:100vh}.admin-sidebar{width:230px}.admin-content{flex:1;min-width:0}.admin-main{min-height:calc(100vh - 70px)}.admin-nav-btn{transition:.2s;cursor:pointer}.admin-nav-btn:hover{transform:translateX(3px)}.admin-mobile-nav{display:none}.admin-password-notice{margin-top:10px;padding:9px 11px;border-radius:10px;background:#FFF7ED;color:#9A3412;font-size:12px;line-height:1.45;font-weight:700;max-width:760px}@media(max-width:768px){.admin-shell{display:block}.admin-sidebar{display:none!important}.admin-mobile-nav{display:block!important}.admin-main{padding-bottom:92px!important}.admin-topbar{padding:14px 16px!important}.admin-title{font-size:17px!important}.admin-password-notice{font-size:11px;margin-top:8px}}@media(min-width:769px){.admin-mobile-nav{display:none!important}}`;

function Sidebar({activePage,onNavigate,onLogout}:Pick<Props,"activePage"|"onNavigate"|"onLogout">){return <aside className="admin-sidebar" style={{minHeight:"100vh",background:C.sidebar,padding:12,display:"flex",flexDirection:"column",flexShrink:0,position:"sticky",top:0}}><div style={{padding:"14px 8px",color:"white",fontWeight:900}}>🎓 Learner's Guide</div><nav style={{flex:1,overflowY:"auto"}}>{NAV.map(item=><button className="admin-nav-btn" key={item.key} onClick={()=>onNavigate(item.key)} style={{width:"100%",border:0,borderRadius:12,padding:"12px",margin:"3px 0",textAlign:"left",background:activePage===item.key?C.accent:"transparent",color:"white"}}>{item.icon} {item.label}</button>)}</nav><ChangePassword compact/><button onClick={onLogout} style={{marginTop:10,padding:11,borderRadius:12}}>🚪 Logout</button></aside>}

function MobileNav({activePage,onNavigate,onLogout}:{activePage:AdminPageKey;onNavigate:(p:AdminPageKey)=>void;onLogout:()=>void}){return <div className="admin-mobile-nav" style={{position:"fixed",bottom:0,left:0,right:0,height:92,background:"white",zIndex:50,borderTop:`1px solid ${C.border}`,padding:"7px 8px calc(7px + env(safe-area-inset-bottom))",boxShadow:"0 -4px 18px rgba(0,0,0,.08)"}}><div style={{display:"grid",gridTemplateColumns:"repeat(6,1fr)",gap:4,overflowX:"auto",height:"100%"}}>{NAV.map(i=><button key={i.key} onClick={()=>onNavigate(i.key)} aria-label={i.label} style={{border:0,borderRadius:10,background:activePage===i.key?C.accent:"transparent",color:activePage===i.key?"white":C.text,minWidth:54,fontSize:11,fontWeight:700,padding:"5px 2px",cursor:"pointer"}}><span style={{fontSize:18}}>{i.icon}</span><br/>{i.label}</button>)}<button onClick={onLogout} aria-label="Logout" style={{border:0,borderRadius:10,background:"transparent",color:C.text,minWidth:54,fontSize:11,fontWeight:700,padding:"5px 2px",cursor:"pointer"}}><span style={{fontSize:18}}>🚪</span><br/>Logout</button></div></div>}

function TopBar({title,subtitle}:{title:string;subtitle?:string}){return <header className="admin-topbar" style={{padding:"20px 28px",background:"white",borderBottom:`1px solid ${C.border}`}}><div className="admin-title" style={{fontWeight:900,fontSize:20}}>{title}</div>{subtitle&&<div style={{fontSize:13,color:C.sub}}>{subtitle}</div>}<div className="admin-password-notice">🔐 Default account passwords: Student <b>Student@1234</b> · Teacher <b>Teacher@1234</b> · Parent <b>Parent@1234</b></div></header>}

export default function AdminLayout({activePage,onNavigate,onLogout,title,subtitle,children}:Props){return <div className="admin-shell" style={{background:C.bg}}><style>{ADMIN_CSS}</style><Sidebar activePage={activePage} onNavigate={onNavigate} onLogout={onLogout}/><div className="admin-content"><TopBar title={title} subtitle={subtitle}/><main className="admin-main">{children}</main></div><MobileNav activePage={activePage} onNavigate={onNavigate} onLogout={onLogout}/></div>}
