import { useEffect, useState } from "react";
import { supabase } from "@/lg/supabase";

type Message={message_id:string;institute_id:string;subject:string;body:string;created_at:string;read_at:string|null};

export function PlatformInboxPage(){
  const [rows,setRows]=useState<Message[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=async()=>{setError("");try{const {data,error:e}=await supabase.rpc("platform_get_my_institute_messages");if(e)throw e;setRows((data||[]) as Message[])}catch(e){setError(e instanceof Error?e.message:"Unable to load platform messages.")}finally{setLoading(false)}};
  useEffect(()=>{void load();const channel=supabase.channel("platform-institute-messages").on("postgres_changes",{event:"*",schema:"public",table:"notifications"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[]);
  const open=async(row:Message)=>{if(!row.read_at){await supabase.rpc("platform_mark_institute_message_read",{p_message_id:row.message_id});setRows(items=>items.map(x=>x.message_id===row.message_id?{...x,read_at:new Date().toISOString()}:x))}};
  return <div style={{maxWidth:920,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",gap:12,marginBottom:18}}><div><div style={{fontSize:11,fontWeight:900,letterSpacing:1.5,color:"#4f46e5"}}>PLATFORM COMMUNICATIONS</div><h2 style={{margin:"5px 0"}}>Mahin Inbox</h2><p style={{margin:0,color:"#64748b"}}>Messages sent by the Mahin platform team to your institute administration.</p></div><button type="button" onClick={()=>void load()} style={{border:0,borderRadius:10,padding:"9px 12px",background:"#eef2ff",color:"#4338ca",fontWeight:800}}>Refresh</button></div>{error&&<div role="alert" style={{padding:12,borderRadius:12,background:"#fff1f2",color:"#b42318",marginBottom:12}}>{error}</div>}{loading?<div style={{padding:30,textAlign:"center",color:"#64748b"}}>Loading messages…</div>:!rows.length?<div style={{background:"#fff",border:"1px solid #e7ebf2",borderRadius:18,padding:34,textAlign:"center",color:"#64748b"}}>No platform messages yet.</div>:rows.map(row=><article key={row.message_id} onClick={()=>void open(row)} style={{background:"#fff",border:"1px solid "+(row.read_at?"#e7ebf2":"#c7d2fe"),borderRadius:18,padding:18,marginBottom:10,cursor:"pointer",boxShadow:row.read_at?"none":"0 8px 24px rgba(79,70,229,.08)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><div style={{fontSize:11,fontWeight:900,color:"#4f46e5"}}>{row.read_at?"":"NEW · "}MAHIN PLATFORM</div><h3 style={{margin:"5px 0"}}>{row.subject}</h3></div><time style={{fontSize:11,color:"#64748b"}}>{new Date(row.created_at).toLocaleString("en-IN")}</time></div><p style={{whiteSpace:"pre-wrap",lineHeight:1.6,color:"#334155",marginBottom:0}}>{row.body}</p></article>)}</div>;
}