import React,{useEffect,useState}from"react";
import {C}from"@/lg/data";
import {supabase}from"@/lg/supabase";
import {getCurrentInstituteContext}from"@/lg/tenant";

const fmt=d=>d?new Date(`${d}T00:00:00`).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"}):"—";
const days=(a,b)=>!a||!b?0:Math.max(1,Math.round((new Date(`${b}T00:00:00`)-new Date(`${a}T00:00:00`))/86400000)+1);
const statusMeta={pending:{label:"Pending",icon:"⏳",bg:"#FFF7ED",fg:"#C2410C",dot:"#F59E0B"},approved:{label:"Approved",icon:"✓",bg:"#ECFDF5",fg:"#047857",dot:"#10B981"},rejected:{label:"Rejected",icon:"×",bg:"#FEF2F2",fg:"#B91C1C",dot:"#EF4444"},cancelled:{label:"Cancelled",icon:"—",bg:"#F1F5F9",fg:"#475569",dot:"#94A3B8"}};
const input={width:"100%",boxSizing:"border-box",border:"1px solid #E2E8F0",borderRadius:14,padding:"12px 13px",background:"#fff",color:"#182044",fontSize:14,outline:"none",fontFamily:"inherit"};
function Status({value}){const m=statusMeta[value]||statusMeta.pending;return <span style={{display:"inline-flex",alignItems:"center",gap:6,padding:"6px 10px",borderRadius:999,background:m.bg,color:m.fg,fontSize:11,fontWeight:900}}><span style={{width:7,height:7,borderRadius:"50%",background:m.dot}}/>{m.icon} {m.label}</span>}
export function LeaveRequests({user,student,canReview=false}){
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(""),[form,setForm]=useState({from_date:"",to_date:"",reason:"",note:""});
 const studentId=String(student?.id||student?.sid||"");
 const load=async()=>{setLoading(true);setError("");try{const context=await getCurrentInstituteContext();const instituteId=context.membership?.institute_id;if(!instituteId)throw new Error("An active institute workspace must be selected.");let q=supabase.from("leave_requests").select("id,student_id,requested_by,from_date,to_date,reason,note,attachment_path,status,reviewed_by,reviewed_at,rejection_reason,created_at,updated_at").eq("institute_id",instituteId).order("created_at",{ascending:false});if(canReview)q=q.limit(200);else if(studentId)q=q.eq("student_id",studentId);else q=q.eq("requested_by",user.id);const{data,error:e}=await q;if(e)throw e;setRows(data||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load leave requests.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[studentId,user?.id,canReview]);
 const submit=async()=>{if(!studentId)return setError("Student profile is not available.");if(!form.from_date||!form.to_date||!form.reason.trim())return setError("Please complete the dates and reason.");if(form.to_date<form.from_date)return setError("The end date cannot be before the start date.");setBusy("submit");setError("");try{const{error:e}=await getCurrentInstituteContext().then(context=>{const instituteId=context.membership?.institute_id;if(!instituteId)throw new Error("An active institute workspace must be selected.");return supabase.from("leave_requests").insert({student_id:studentId,requested_by:user.id,from_date:form.from_date,to_date:form.to_date,reason:form.reason.trim(),note:form.note.trim()||null,institute_id:instituteId})});if(e)throw e;setForm({from_date:"",to_date:"",reason:"",note:""});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to submit leave request.")}finally{setBusy("")}};
 const review=async(id,status)=>{setBusy(`${id}:${status}`);setError("");try{let rejection_reason=null;if(status==="rejected"){rejection_reason=window.prompt("Reason for rejection:")?.trim()||null;if(!rejection_reason)return}const{error:e}=await getCurrentInstituteContext().then(context=>{const instituteId=context.membership?.institute_id;if(!instituteId)throw new Error("An active institute workspace must be selected.");return supabase.from("leave_requests").update({status,reviewed_by:user.id,reviewed_at:new Date().toISOString(),rejection_reason}).eq("institute_id",instituteId).eq("id",id).eq("status","pending")});if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update leave request.")}finally{setBusy("")}};
 const pending=rows.filter(r=>r.status==="pending").length,approved=rows.filter(r=>r.status==="approved").length;
 return <div style={{fontFamily:"Inter,ui-sans-serif,system-ui,sans-serif",color:"#182044"}}>
  <div style={{padding:"2px 2px 18px"}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:46,height:46,borderRadius:15,display:"grid",placeItems:"center",background:"linear-gradient(135deg,#635BDF,#8B5CF6)",color:"#fff",fontSize:22,boxShadow:"0 8px 22px rgba(99,91,223,.24)"}}>🏖️</div><div><div style={{fontSize:22,fontWeight:950,letterSpacing:-.6}}>{canReview?"Leave Requests":"Leave"}</div><div style={{fontSize:12,color:"#64748B",marginTop:3}}>{canReview?"Review and manage student leave":"Plan an absence and keep attendance clear"}</div></div></div></div>
  {!canReview&&<><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10,marginBottom:14}}><div style={{padding:"12px 14px",borderRadius:16,background:"linear-gradient(135deg,#F5F3FF,#EEF2FF)",border:"1px solid #E9E5FF"}}><div style={{fontSize:11,color:"#64748B",fontWeight:800}}>PENDING</div><div style={{fontSize:22,fontWeight:950,marginTop:3}}>{pending}</div></div><div style={{padding:"12px 14px",borderRadius:16,background:"#ECFDF5",border:"1px solid #D1FAE5"}}><div style={{fontSize:11,color:"#64748B",fontWeight:800}}>APPROVED</div><div style={{fontSize:22,fontWeight:950,marginTop:3}}>{approved}</div></div></div>
   <div style={{borderRadius:20,padding:16,background:"linear-gradient(145deg,#FFFFFF,#F8FAFC)",border:"1px solid #E2E8F0",boxShadow:"0 12px 35px rgba(15,23,42,.07)",marginBottom:18}}><div style={{fontWeight:900,fontSize:15}}>Request time off</div><div style={{fontSize:12,color:"#64748B",margin:"4px 0 14px"}}>Choose the dates and tell your institute why you'll be away.</div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10}}><label style={{fontSize:11,fontWeight:800,color:"#64748B"}}>FROM<input aria-label="From date" type="date" value={form.from_date} onChange={e=>setForm({...form,from_date:e.target.value})} style={{...input,marginTop:5}}/></label><label style={{fontSize:11,fontWeight:800,color:"#64748B"}}>TO<input aria-label="To date" type="date" value={form.to_date} onChange={e=>setForm({...form,to_date:e.target.value})} style={{...input,marginTop:5}}/></label></div><input aria-label="Leave reason" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Reason for leave" style={{...input,marginTop:10}}/><textarea aria-label="Additional note" value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Additional note (optional)" style={{...input,marginTop:10,minHeight:76,resize:"vertical"}}/><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,marginTop:12}}>{form.from_date&&form.to_date&&form.to_date>=form.from_date?<span style={{fontSize:11,color:"#64748B",fontWeight:700}}>{days(form.from_date,form.to_date)} day{days(form.from_date,form.to_date)===1?"":"s"} requested</span>:<span/>}<button disabled={!!busy} onClick={()=>void submit()} style={{border:0,borderRadius:13,padding:"11px 16px",background:"linear-gradient(135deg,#635BDF,#5148D9)",color:"#fff",fontWeight:900,boxShadow:"0 8px 18px rgba(99,91,223,.22)",cursor:busy?"wait":"pointer"}}>{busy==="submit"?"Submitting…":"Submit request →"}</button></div></div></>}
  {error&&<div role="alert" style={{padding:"11px 13px",borderRadius:13,background:"#FEF2F2",border:"1px solid #FECACA",color:"#B91C1C",fontSize:12,fontWeight:700,marginBottom:12}}>{error}</div>}
  <div style={{fontWeight:900,fontSize:14,marginBottom:9}}>{canReview?"Requests awaiting review":"Request history"}</div>
  {loading?<div style={{padding:28,textAlign:"center",color:"#64748B",background:"#fff",borderRadius:16,border:"1px solid #E2E8F0"}}>Loading requests…</div>:!rows.length?<div style={{padding:30,textAlign:"center",background:"#fff",borderRadius:18,border:"1px dashed #CBD5E1"}}><div style={{fontSize:30}}>🌤️</div><div style={{fontWeight:900,marginTop:7}}>No leave requests yet</div><div style={{fontSize:12,color:"#64748B",marginTop:4}}>{canReview?"New requests will appear here.":"Your submitted requests will appear here."}</div></div>:<div style={{display:"grid",gap:10}}>{rows.map(r=>{const d=days(r.from_date,r.to_date);return <div key={r.id} style={{background:"#fff",border:"1px solid #E2E8F0",borderRadius:18,padding:14,boxShadow:"0 5px 18px rgba(15,23,42,.045)"}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"flex-start"}}><div><div style={{fontSize:15,fontWeight:900}}>{fmt(r.from_date)} <span style={{color:"#94A3B8",fontWeight:500}}>→</span> {fmt(r.to_date)}</div><div style={{fontSize:11,color:"#64748B",marginTop:4}}>{d} day{d===1?"":"s"} · {r.reason}</div></div><Status value={r.status}/></div>{r.note&&<div style={{marginTop:10,padding:10,borderRadius:12,background:"#F8FAFC",fontSize:12,color:"#475569"}}>{r.note}</div>}{r.rejection_reason&&<div style={{marginTop:10,padding:10,borderRadius:12,background:"#FEF2F2",color:"#B91C1C",fontSize:12}}><strong>Rejection reason:</strong> {r.rejection_reason}</div>}{canReview&&r.status==="pending"&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:12}}><button disabled={!!busy} onClick={()=>void review(r.id,"approved")} style={{border:0,borderRadius:12,padding:"10px",background:"#ECFDF5",color:"#047857",fontWeight:900,cursor:"pointer"}}>{busy===`${r.id}:approved`?"Approving…":"✓ Approve"}</button><button disabled={!!busy} onClick={()=>void review(r.id,"rejected")} style={{border:0,borderRadius:12,padding:"10px",background:"#FEF2F2",color:"#B91C1C",fontWeight:900,cursor:"pointer"}}>{busy===`${r.id}:rejected`?"Rejecting…":"× Reject"}</button></div>}</div>})}</div>}
 </div>;
}
