import React,{useEffect,useState}from"react";
import {C}from"@/lg/data";
import {supabase}from"@/lg/supabase";
import {Card,Badge,Sec}from"@/lg/ui";

const fmt=d=>d?new Date(`${d}T00:00:00`).toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"}):"—";
const days=(a,b)=>{if(!a||!b)return 0;return Math.max(1,Math.round((new Date(`${b}T00:00:00`)-new Date(`${a}T00:00:00`))/86400000)+1)};

export function LeaveRequests({user,student,canReview=false}){
  const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(""),[form,setForm]=useState({from_date:"",to_date:"",reason:"",note:""});
  const studentId=String(student?.id||student?.sid||"");
  const load=async()=>{setLoading(true);setError("");try{let q=supabase.from("leave_requests").select("id,student_id,requested_by,from_date,to_date,reason,note,attachment_path,status,reviewed_by,reviewed_at,rejection_reason,created_at,updated_at").order("created_at",{ascending:false});if(canReview)q=q.limit(200);else if(studentId)q=q.eq("student_id",studentId);else q=q.eq("requested_by",user.id);const{data,error:e}=await q;if(e)throw e;setRows(data||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load leave requests.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[studentId,user?.id,canReview]);
  const submit=async()=>{if(!studentId)return setError("Student profile is not available.");if(!form.from_date||!form.to_date||!form.reason.trim())return setError("From date, to date and reason are required.");if(form.to_date<form.from_date)return setError("To date cannot be before from date.");setBusy("submit");setError("");try{const{error:e}=await supabase.from("leave_requests").insert({student_id:studentId,requested_by:user.id,from_date:form.from_date,to_date:form.to_date,reason:form.reason.trim(),note:form.note.trim()||null});if(e)throw e;setForm({from_date:"",to_date:"",reason:"",note:""});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to submit leave request.")}finally{setBusy("")}};
  const review=async(id,status)=>{setBusy(`${id}:${status}`);setError("");try{const patch={status,reviewed_by:user.id,reviewed_at:new Date().toISOString(),rejection_reason:status==="rejected"?window.prompt("Reason for rejection:")||null:null};if(status==="rejected"&&!patch.rejection_reason)return;const{error:e}=await supabase.from("leave_requests").update(patch).eq("id",id).eq("status","pending");if(e)throw e;await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update leave request.")}finally{setBusy("")}};
  return <div><Sec title={canReview?"Leave Requests 🏖️":"My Leave Requests 🏖️"}/>{!canReview&&<Card style={{marginBottom:14}}><div style={{fontWeight:900,marginBottom:10}}>Request leave</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><input type="date" value={form.from_date} onChange={e=>setForm({...form,from_date:e.target.value})}/><input type="date" value={form.to_date} onChange={e=>setForm({...form,to_date:e.target.value})}/></div><input value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Reason" style={{width:"100%",marginTop:10}}/><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Additional note (optional)" style={{width:"100%",marginTop:10,minHeight:80}}/><button disabled={!!busy} onClick={()=>void submit()} style={{marginTop:10,border:0,borderRadius:10,padding:"10px 14px",background:C.accent,color:"#fff",fontWeight:800}}>{busy==="submit"?"Submitting…":"Submit Leave Request"}</button></Card>}{error&&<Card style={{color:C.red,background:"#FEF2F2",marginBottom:12}}>{error}</Card>}{loading?<Card>Loading leave requests…</Card>:!rows.length?<Card style={{color:C.sub}}>No leave requests found.</Card>:rows.map(r=><Card key={r.id} style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"flex-start"}}><div><div style={{fontWeight:900}}>{fmt(r.from_date)} → {fmt(r.to_date)}</div><div style={{fontSize:12,color:C.sub,marginTop:3}}>{days(r.from_date,r.to_date)} day{days(r.from_date,r.to_date)===1?"":"s"} · {r.reason}</div>{r.note&&<div style={{fontSize:12,color:C.sub,marginTop:6}}>{r.note}</div>}{r.rejection_reason&&<div style={{fontSize:12,color:C.red,marginTop:6}}>Reason: {r.rejection_reason}</div>}</div><Badge label={r.status}/></div>{canReview&&r.status==="pending"&&<div style={{display:"flex",gap:8,marginTop:12}}><button disabled={!!busy} onClick={()=>void review(r.id,"approved")} style={{border:0,borderRadius:10,padding:"8px 12px",background:C.green,color:"#fff",fontWeight:800}}>{busy===`${r.id}:approved`?"Approving…":"Approve"}</button><button disabled={!!busy} onClick={()=>void review(r.id,"rejected")} style={{border:0,borderRadius:10,padding:"8px 12px",background:C.red,color:"#fff",fontWeight:800}}>{busy===`${r.id}:rejected`?"Rejecting…":"Reject"}</button></div>}</Card>)}</div>;
}
