import React,{useEffect,useState}from"react";
import {supabase}from"@/lg/supabase";
import {LeaveRequests}from"@/lg/LeaveRequests";

const clean=v=>(v||"").replace(/\s+/g," ").trim().toLowerCase();
function findNav(){
 if(typeof document==="undefined")return null;
 const els=[...document.querySelectorAll("body *")].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0});
 const exact=(names)=>els.find(e=>names.includes(clean(e.textContent)));
 const anchors=[exact(["home","🏠 home"]),exact(["schedule","📅 schedule"]),exact(["materials","📚 materials"]),exact(["hw","📝 hw"]),exact(["exams","📋 exams"]),exact(["results","🏆 results"]),exact(["attend.","attend","✅ attend.","✅ attend"])].filter(Boolean);
 if(anchors.length>=3){
  let n=anchors[0];
  while(n){const ok=anchors.every(a=>n.contains(a));if(ok){const r=n.getBoundingClientRect(),s=getComputedStyle(n),controls=n.querySelectorAll("button,a,[role=button]");if(r.bottom>=window.innerHeight-45&&controls.length>=5&&(r.width>=Math.min(window.innerWidth*.7,300)))return n}n=n.parentElement}
 }
 const candidates=els.filter(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e),controls=e.querySelectorAll("button,a,[role=button]");return r.bottom>=window.innerHeight-45&&r.height>=48&&r.height<=180&&r.width>=Math.min(window.innerWidth*.7,300)&&controls.length>=5&&(s.position==="fixed"||s.position==="sticky"||s.display==="flex"||s.display==="grid")}).sort((a,b)=>a.getBoundingClientRect().width-b.getBoundingClientRect().width);
 return candidates[0]||null;
}
function navButton(onOpen){const b=document.createElement("button");b.type="button";b.dataset.lgLeaveNav="1";b.setAttribute("aria-label","Leave");b.innerHTML='<span style="font-size:21px;line-height:1">🏖️</span><span style="font-size:10px;font-weight:800;margin-top:3px;white-space:nowrap">Leave</span>';b.style.cssText="appearance:none;-webkit-appearance:none;flex:1 1 0!important;min-width:0!important;width:0!important;height:100%;margin:0;border:0;border-left:1px solid #e8ebf1;background:transparent;color:#64748b;padding:5px 1px calc(5px + env(safe-area-inset-bottom,0px));font:inherit;display:flex;flex-direction:column;align-items:center;justify-content:center;box-sizing:border-box;cursor:pointer;touch-action:manipulation";b.onclick=onOpen;return b}
function mount(onOpen){const nav=findNav();if(!nav)return null;const old=nav.querySelector('[data-lg-leave-nav="1"]');if(old)return old;const b=navButton(onOpen);nav.style.setProperty("display","flex","important");nav.style.setProperty("flex-direction","row","important");nav.style.setProperty("flex-wrap","nowrap","important");nav.style.setProperty("align-items","stretch","important");nav.style.setProperty("overflow","hidden","important");[...nav.children].forEach(c=>{if(c instanceof HTMLElement){c.style.setProperty("flex","1 1 0","important");c.style.setProperty("min-width","0","important");c.style.setProperty("width","0","important");c.style.setProperty("box-sizing","border-box","important")}});nav.appendChild(b);return b}
export function LeaveAccess({user,student,canReview=false}){
 const[open,setOpen]=useState(false),[resolvedStudent,setResolvedStudent]=useState(student||null);
 useEffect(()=>{let live=true;(async()=>{if(student||canReview||!user)return;try{if(user.role==="student"&&user.ref){const{data}=await supabase.from("students").select("id,name,sid,cls,sec").eq("id",user.ref).maybeSingle();if(live&&data)setResolvedStudent(data);return}if(user.role==="parent"){const{data:links}=await supabase.from("parent_student_links").select("student_id,status").eq("parent_auth_id",user.id).eq("status","active").limit(20);const ids=[...new Set((links||[]).map(x=>String(x.student_id)).filter(Boolean))];if(ids.length){const{data}=await supabase.from("students").select("id,name,sid,cls,sec").in("id",ids).order("name");if(live)setResolvedStudent(data?.[0]||null)}}}catch{}})();return()=>{live=false}},[student,canReview,user?.id,user?.ref,user?.role]);
 useEffect(()=>{if(!user||canReview)return;let b=null,tries=0,observer;const openLeave=()=>setOpen(true);const attempt=()=>{if(!b)b=mount(openLeave);if(!b&&tries++<120)window.setTimeout(attempt,150)};attempt();observer=new MutationObserver(()=>{if(!document.querySelector('[data-lg-leave-nav="1"]')){b=null;attempt()}});observer.observe(document.body,{childList:true,subtree:true});window.addEventListener("resize",attempt,{passive:true});return()=>{observer?.disconnect();window.removeEventListener("resize",attempt);if(b?.parentNode)b.parentNode.removeChild(b)}} , [user,canReview]);
 if(!user)return null;
 return <>{canReview&&<button type="button" onClick={()=>setOpen(true)} style={{position:"fixed",right:16,bottom:"calc(76px + env(safe-area-inset-bottom,0px))",zIndex:1200,border:"1px solid rgba(255,255,255,.28)",borderRadius:999,padding:"11px 15px",background:"rgba(24,32,68,.94)",backdropFilter:"blur(14px)",color:"#fff",fontWeight:900}}>🏖️ Leave Requests</button>}{open&&<div role="dialog" aria-modal="true" onClick={()=>setOpen(false)} style={{position:"fixed",inset:0,zIndex:1300,background:"rgba(15,23,42,.52)",backdropFilter:"blur(5px)",display:"flex",alignItems:"center",justifyContent:"center",padding:16}}><div onClick={e=>e.stopPropagation()} style={{width:"min(720px,100%)",maxHeight:"90vh",overflowY:"auto",background:"#f8fafc",borderRadius:22,padding:18,boxShadow:"0 24px 70px rgba(15,23,42,.28)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><div><div style={{fontSize:11,fontWeight:800,color:"#635bdf",letterSpacing:1,textTransform:"uppercase"}}>Attendance & Leave</div><h2 style={{margin:"3px 0 0",fontSize:22,color:"#182044"}}>{canReview?"Leave Requests":"Leave"}</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close leave" style={{border:0,borderRadius:10,padding:"8px 11px",background:"#e9edf5",cursor:"pointer"}}>✕</button></div><LeaveRequests user={user} student={resolvedStudent} canReview={canReview}/></div></div>}</>;
}
