import React,{useEffect,useState}from"react";
import {supabase}from"@/lg/supabase";
import {LeaveRequests}from"@/lg/LeaveRequests";

export function LeaveAccess({user,student,canReview=false}){
 const[open,setOpen]=useState(false),[resolvedStudent,setResolvedStudent]=useState(student||null);
 useEffect(()=>{let live=true;(async()=>{if(student||canReview||!user)return;try{if(user.role==="student"&&user.ref){const{data}=await supabase.from("students").select("id,name,sid,cls,sec").eq("id",user.ref).maybeSingle();if(live&&data)setResolvedStudent(data);return}if(user.role==="parent"){const{data:links}=await supabase.from("parent_student_links").select("student_id,status").eq("parent_auth_id",user.id).eq("status","active").limit(20);const ids=[...new Set((links||[]).map(x=>String(x.student_id)).filter(Boolean))];if(!ids.length)return;const{data:students}=await supabase.from("students").select("id,name,sid,cls,sec").in("id",ids).order("name");if(live)setResolvedStudent(students?.[0]||null)}}catch{}})();return()=>{live=false}},[student,canReview,user?.id,user?.ref,user?.role]);
 if(!user)return null;
 const mobileNavButton=!canReview&&<button type="button" onClick={()=>setOpen(true)} aria-label="Open Leave" style={{position:"fixed",right:0,bottom:0,width:"12.5vw",minWidth:78,maxWidth:118,height:"84px",zIndex:1100,border:0,borderTop:"1px solid #eef1f7",background:"rgba(255,255,255,.98)",color:open?"#5B4FE8":"#64748b",padding:"8px 3px calc(8px + env(safe-area-inset-bottom,0px))",fontFamily:"inherit",fontWeight:800,textAlign:"center",cursor:"pointer",touchAction:"manipulation",boxSizing:"border-box",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",boxShadow:"0 -4px 14px rgba(15,23,42,.04)"}}><span style={{fontSize:22,lineHeight:1.05}}>🏖️</span><span style={{fontSize:11,fontWeight:800,marginTop:4}}>Leave</span></button>;
 return <>{mobileNavButton}{canReview&&<button type="button" onClick={()=>setOpen(true)} aria-label="Open leave requests" style={{position:"fixed",right:16,bottom:"calc(76px + env(safe-area-inset-bottom,0px))",zIndex:1200,border:"1px solid rgba(255,255,255,.28)",borderRadius:999,padding:"11px 15px",background:"rgba(24,32,68,.94)",backdropFilter:"blur(14px)",WebkitBackdropFilter:"blur(14px)",color:"#fff",fontWeight:900,boxShadow:"0 10px 28px rgba(15,23,42,.22)",cursor:"pointer"}}>🏖️ Leave Requests</button>}{open&&<div role="dialog" aria-modal="true" onClick={()=>setOpen(false)} style={{position:"fixed",inset:0,zIndex:1300,background:"rgba(15,23,42,.52)",backdropFilter:"blur(5px)",display:"flex",alignItems:"center",justifyContent:"center",padding:16}}><div onClick={e=>e.stopPropagation()} style={{width:"min(720px,100%)",maxHeight:"90vh",overflowY:"auto",background:"#f8fafc",borderRadius:22,padding:18,boxShadow:"0 24px 70px rgba(15,23,42,.28)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginBottom:12}}><div><div style={{fontSize:11,fontWeight:800,color:"#635bdf",letterSpacing:1,textTransform:"uppercase"}}>Attendance & Leave</div><h2 style={{margin:"3px 0 0",fontSize:22,color:"#182044"}}>{canReview?"Leave Requests":"Leave"}</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close leave" style={{border:0,borderRadius:10,padding:"8px 11px",background:"#e9edf5",cursor:"pointer",fontSize:16}}>✕</button></div><LeaveRequests user={user} student={resolvedStudent} canReview={canReview}/></div></div>}</>;
}
