import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lg/supabase";
import { C } from "@/lg/data";
import { Badge, Card, Sec, Shell, AppBar } from "@/lg/ui";
import { ParentNotifications } from "@/lg/ParentNotifications";
import { ParentHomework } from "@/lg/ParentHomework";

export function ParentApp({ user, onLogout }) {
  const [children,setChildren]=useState([]); const [selectedId,setSelectedId]=useState(null); const [attendance,setAttendance]=useState([]); const [fees,setFees]=useState([]); const [tests,setTests]=useState([]); const [results,setResults]=useState([]); const [homework,setHomework]=useState([]); const [materials,setMaterials]=useState([]); const [batches,setBatches]=useState([]); const [timetable,setTimetable]=useState([]); const [tab,setTab]=useState("home"); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [showNotif,setShowNotif]=useState(false);
  const selected=useMemo(()=>children.find(c=>String(c.id)===String(selectedId))||children[0]||null,[children,selectedId]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const{data:auth,error:ae}=await supabase.auth.getUser();if(ae)throw ae;const authId=auth?.user?.id;if(!authId)throw new Error("Parent session expired. Please sign in again.");const{data:links,error:le}=await supabase.from("parent_student_links").select("student_id,status").eq("parent_auth_id",authId).eq("status","active");if(le)throw le;const ids=[...new Set((links||[]).map(x=>String(x.student_id)).filter(Boolean))];if(!ids.length&&user?.ref)ids.push(String(user.ref));const{data:students,error:se}=await supabase.from("students").select("id,name,sid,cls,sec").in("id",ids);if(se)throw se;setChildren(students||[]);setSelectedId(cur=>cur&&students?.some(s=>String(s.id)===String(cur))?cur:students?.[0]?.id||null);const{data:members,error:me}=await supabase.from("batch_students").select("student_id,batch_id,status").in("student_id",ids).eq("status","active");if(me)throw me;const bid=[...new Set((members||[]).map(x=>String(x.batch_id)).filter(Boolean))];const [br,tr,ar,fr,hw,test]=await Promise.all([bid.length?supabase.from("batches").select("id,name,cls,sec,status").in("id",bid):Promise.resolve({data:[],error:null}),bid.length?supabase.from("timetable_entries").select("id,batch_id,subject_name,subject,start_time,end_time,status,day,day_of_week").in("batch_id",bid).eq("status","active"):Promise.resolve({data:[],error:null}),supabase.from("attendance").select("id,sid,date,status").in("sid",ids).order("date",{ascending:false}),supabase.from("fees").select("id,sid,desc,amount,status,due").in("sid",ids).order("due"),bid.length?supabase.from("homework").select("id,batch_id,subject,title,desc,given,due,created_at,pdfname").in("batch_id",bid).order("created_at",{ascending:false}):Promise.resolve({data:[],error:null}),bid.length?supabase.from("tests").select("id,title,description,batch_id,subject,test_date,total_marks,status").in("batch_id",bid).order("test_date"):Promise.resolve({data:[],error:null})]);for(const r of[br,tr,ar,fr,hw,test])if(r.error)throw r.error;setBatches(members||[]);setTimetable(tr.data||[]);setAttendance(ar.data||[]);setFees(fr.data||[]);setHomework(hw.data||[]);setTests(test.data||[]);const tids=(test.data||[]).map(x=>String(x.id));if(tids.length){const{data:rr,error:re}=await supabase.from("test_results").select("id,student_id,test_id,marks").in("test_id",tids);if(re)throw re;setResults(rr||[])}else setResults([]);if(bid.length){const{data:mat,error:mate}=await supabase.from("materials").select("id,title,name,storage_path,mime_type,batch_id,created_at").in("batch_id",bid).order("created_at",{ascending:false});if(mate)throw mate;setMaterials(mat||[])}else setMaterials([])}catch(e){setError(e instanceof Error?e.message:"Unable to load parent data.")}finally{setLoading(false)}},[user?.ref]);
  useEffect(()=>{void load()},[load]);
  const childBatches=batches.filter(m=>String(m.student_id)===String(selected?.id)); const ids=new Set(childBatches.map(m=>String(m.batch_id))); const childAttendance=attendance.filter(a=>String(a.sid)===String(selected?.id)); const childFees=fees.filter(f=>String(f.sid)===String(selected?.id)); const childTests=tests.filter(t=>ids.has(String(t.batch_id))); const childResults=results.filter(r=>String(r.student_id)===String(selected?.id)); const childHomework=homework.filter(h=>ids.has(String(h.batch_id))); const childTimetable=timetable.filter(t=>ids.has(String(t.batch_id))); const childMaterials=materials.filter(m=>ids.has(String(m.batch_id))); const rate=childAttendance.length?Math.round(childAttendance.filter(a=>String(a.status).toLowerCase()==="present").length/childAttendance.length*100):null;
  const content=loading?<Card>Loading your child's data…</Card>:error?<Card><div style={{color:C.red}}>{error}</div><button onClick={()=>void load()}>Try again</button></Card>:!selected?<Card>No student is linked to this parent account.</Card>:<div>{children.length>1&&<Card style={{marginBottom:12}}><select value={selected.id} onChange={e=>setSelectedId(e.target.value)}>{children.map(c=><option key={c.id} value={c.id}>{c.name} · {c.sid}</option>)}</select></Card>}<Card style={{marginBottom:14}}><h2 style={{margin:0}}>{selected.name}</h2><div style={{fontSize:12,color:C.sub}}>Class {selected.cls}-{selected.sec} · {selected.sid}</div></Card>{tab==="home"&&<><Sec title="Summary"/><Card>Attendance: {rate==null?"—":`${rate}%`} · Homework: {childHomework.length} · Tests: {childTests.length}</Card></>}{tab==="attendance"&&<><Sec title="Attendance"/>{childAttendance.length?childAttendance.map(a=><Card key={a.id} style={{marginBottom:7,display:"flex",justifyContent:"space-between"}}><span>{a.date}</span><Badge label={a.status}/></Card>):<Card>No attendance records found.</Card>}</>}{tab==="fees"&&<><Sec title="Fees"/>{childFees.length?childFees.map(f=><Card key={f.id} style={{marginBottom:7,display:"flex",justifyContent:"space-between"}}><span>{f.desc||"Fee"}</span><span>₹{Number(f.amount||0).toLocaleString("en-IN")} · {f.status}</span></Card>):<Card>No fee records found.</Card>}</>}{tab==="timetable"&&<><Sec title="Timetable"/>{childTimetable.map(t=><Card key={t.id} style={{marginBottom:7}}>{t.subject_name||t.subject||"Class"} · {String(t.start_time||"").slice(0,5)}–{String(t.end_time||"").slice(0,5)}</Card>)}</>}{tab==="homework"&&<ParentHomework homework={childHomework}/>} {tab==="tests"&&<><Sec title="Tests"/>{childTests.map(t=><Card key={t.id} style={{marginBottom:8}}><b>{t.title}</b><div style={{fontSize:12,color:C.sub}}>{t.subject} · {t.test_date}</div></Card>)}</>}{tab==="results"&&<><Sec title="Results"/>{childResults.map(r=><Card key={r.id} style={{marginBottom:8}}>Score: {r.marks}</Card>)}</>}{tab==="materials"&&<><Sec title="Materials"/>{childMaterials.map(m=><Card key={m.id}>{m.name||m.title}</Card>)}</>}</div>;
  const tabs=[{key:"home",icon:"🏠",label:"Home"},{key:"timetable",icon:"🗓️",label:"Classes"},{key:"attendance",icon:"✅",label:"Attend."},{key:"homework",icon:"📝",label:"HW"},{key:"tests",icon:"📋",label:"Tests"},{key:"results",icon:"🏆",label:"Results"},{key:"materials",icon:"📚",label:"Materials"},{key:"fees",icon:"💰",label:"Fees"}];
  return <><Shell header={<AppBar name={user.name} role="parent" userId={user.id} onLogout={onLogout} onNotif={()=>setShowNotif(true)}/>} tabs={tabs} activeTab={tab} setTab={setTab}>{content}</Shell>{showNotif&&<ParentNotifications onClose={()=>setShowNotif(false)}/>}</>;
}
