import React,{useEffect,useState}from"react";
import {C,lsG}from"@/lg/data";
import {PDFViewer}from"@/lg/panels";
import {ParentNotifications}from"@/lg/ParentNotifications";
import {supabase}from"@/lg/supabase";
import {Card,Badge,Sec,Shell,AppBar}from"@/lg/ui";

const idsForChild=(child)=>[...new Set([child?.id,child?.sid].map(v=>String(v??"").trim()).filter(Boolean))];

function useChildAttendance(child){
  const[rows,setRows]=useState([]),[error,setError]=useState("");
  useEffect(()=>{let live=true;(async()=>{
    setError("");
    const ids=idsForChild(child);
    if(!ids.length){setRows([]);return}
    const{data,error:e}=await supabase.from("attendance").select("id,sid,date,status,by,created_at").in("sid",ids).order("date",{ascending:false}).order("created_at",{ascending:false});
    if(!live)return;
    if(e){setError(e.message);setRows([])}else{const unique=[...new Map((data||[]).map(r=>[String(r.id),r])).values()];setRows(unique)}
  })();return()=>{live=false}},[child?.id,child?.sid]);
  return{rows,error}
}

function useParentChild(user){
  const[child,setChild]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{let live=true;(async()=>{
    setLoading(true);setError("");
    try{
      const ref=String(user?.ref??"").trim();
      if(!ref){setChild(null);return}
      const direct=await supabase.from("students").select("id,name,sid,cls,sec,parentname,parentphone,parent,enroll,status").eq("id",ref).maybeSingle();
      if(direct.error)throw direct.error;
      if(direct.data){if(live)setChild(direct.data);return}
      const linked=await supabase.from("parent_student_links").select("student_id").eq("parent_auth_id",user?.id).eq("status","active");
      if(linked.error)throw linked.error;
      const studentIds=[...new Set((linked.data||[]).map(x=>String(x.student_id||"")).filter(Boolean))];
      if(!studentIds.length){if(live)setChild(null);return}
      const students=await supabase.from("students").select("id,name,sid,cls,sec,parentname,parentphone,parent,enroll,status").in("id",studentIds).limit(1);
      if(students.error)throw students.error;
      if(live)setChild(students.data?.[0]||null);
    }catch(e){if(live){setError(e instanceof Error?e.message:"Unable to load student profile.");setChild(null)}}finally{if(live)setLoading(false)}})();return()=>{live=false}},[user?.id,user?.ref]);
  return{child,loading,error}
}

export function PTHome({child}){const{rows:att}=useChildAttendance(child);const rate=att.length?Math.round(att.filter(a=>String(a.status||"").toLowerCase()==="present").length/att.length*100):null;const hw=child?lsG("homework").filter(h=>h.cls===child.cls&&h.sec===child.sec):[];const ann=lsG("announcements").filter(a=>a.target==="all").slice(0,2);return <div><Card style={{marginBottom:16,background:"linear-gradient(135deg,#22C55E,#16A34A)",border:"none"}}><div style={{fontSize:19,fontWeight:900,color:"#fff"}}>{child?.name}</div><div style={{fontSize:12,color:"rgba(255,255,255,.7)"}}>Class {child?.cls}-{child?.sec} · {child?.sid}</div><div style={{display:"flex",gap:10,marginTop:13}}>{[[rate==null?"—":`${rate}%`,"Attendance"],[hw.length,"HW Pending"]].map(([v,l])=><div key={l} style={{flex:1,background:"rgba(255,255,255,.15)",borderRadius:11,padding:9,textAlign:"center"}}><div style={{fontSize:19,fontWeight:900,color:"#fff"}}>{v}</div><div style={{fontSize:10,color:"rgba(255,255,255,.65)"}}>{l}</div></div>)}</div></Card><Sec title="Recent Attendance 📋"/>{att.slice(0,4).map(a=><Card key={a.id} style={{marginBottom:8,display:"flex",justifyContent:"space-between"}}><div>{a.date}</div><Badge label={a.status}/></Card>)}{!att.length&&<Card style={{color:C.sub}}>No attendance records have been saved for this student yet.</Card>}<Sec title="Announcements 📢"/>{ann.map(a=><Card key={a.id} style={{marginBottom:9}}><div style={{fontWeight:700}}>{a.title}</div><div style={{fontSize:12,color:C.sub}}>{a.desc}</div></Card>)}</div>}

export function PTAttendance({child}){const{rows:att,error}=useChildAttendance(child);const rate=att.length?Math.round(att.filter(a=>String(a.status||"").toLowerCase()==="present").length/att.length*100):null;return <div>{error&&<Card style={{padding:14,color:"#B91C1C",background:"#FEF2F2"}}>{error}</Card>}<Card style={{textAlign:"center",marginBottom:16,padding:26}}><div style={{fontSize:13,color:C.sub}}>Overall Attendance</div><div style={{fontSize:50,fontWeight:900,color:rate==null?C.sub:rate>=85?"#22C55E":rate>=70?"#F59E0B":"#EF4444"}}>{rate==null?"—":`${rate}%`}</div><div style={{fontSize:12,color:C.sub,marginTop:8}}>{att.length?`${att.filter(a=>String(a.status||"").toLowerCase()==="present").length} present · ${att.filter(a=>String(a.status||"").toLowerCase()==="absent").length} absent · ${att.filter(a=>String(a.status||"").toLowerCase()==="leave").length} leave`:"No records yet"}</div></Card><Sec title="Attendance Log"/>{att.length?[...att].map(a=><Card key={a.id} style={{marginBottom:7,display:"flex",justifyContent:"space-between"}}><div>{a.date}</div><Badge label={a.status}/></Card>):<Card style={{padding:20,color:C.sub}}>No attendance records have been saved for this student yet.</Card>}</div>}

export function PTResults({child}){const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{let live=true;(async()=>{setLoading(true);setError("");try{if(!child?.id){setRows([]);return}const{data:results,error:resultError}=await supabase.from("test_results").select("id,test_id,student_id,marks,remarks,created_at,updated_at").eq("student_id",String(child.id));if(resultError)throw resultError;const ids=[...new Set((results||[]).map(r=>String(r.test_id)).filter(Boolean))];const{data:tests,error:testError}=ids.length?await supabase.from("tests").select("id,title,subject,test_date,total_marks").in("id",ids):{data:[],error:null};if(testError)throw testError;const testMap=new Map((tests||[]).map(t=>[String(t.id),t]));const mapped=(results||[]).map(r=>{const t=testMap.get(String(r.test_id)),marks=Number(r.marks),total=Number(t?.total_marks);return{...r,test:t,percentage:Number.isFinite(marks)&&Number.isFinite(total)&&total>0?(marks/total)*100:null}});if(live)setRows(mapped)}catch(e){if(live){setError(e instanceof Error?e.message:"Unable to load results.");setRows([])}}finally{if(live)setLoading(false)}})();return()=>{live=false}},[child?.id]);return <div>{error&&<Card style={{padding:14,color:"#B91C1C",background:"#FEF2F2",marginBottom:10}}>{error}</Card>}<Sec title="Test Results 📊"/>{loading?<Card style={{padding:20,color:C.sub}}>Loading results…</Card>:!rows.length?<Card style={{padding:20,color:C.sub}}>No test results have been published yet.</Card>:rows.map(r=>{const marks=r.marks??"—",total=r.test?.total_marks??"—";return <Card key={r.id} style={{marginBottom:10,padding:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:12}}><div style={{minWidth:0}}><div style={{fontWeight:800,fontSize:15}}>{r.test?.title||"Test"}</div><div style={{fontSize:12,color:C.sub,marginTop:4}}>{r.test?.subject||"—"} · {r.test?.test_date||"—"}</div></div><div style={{textAlign:"right",flexShrink:0}}><div style={{fontSize:25,fontWeight:950,lineHeight:1}}>{marks}<span style={{fontSize:17,color:C.sub,fontWeight:800}}>/{total}</span></div><div style={{fontSize:10,color:C.sub,marginTop:5,fontWeight:700}}>MARKS</div></div></div>{r.percentage!=null&&<div style={{marginTop:13}}><div style={{display:"flex",justifyContent:"space-between",fontSize:11,color:C.sub,fontWeight:700,marginBottom:5}}><span>Performance</span><span>{Math.round(r.percentage)}%</span></div><div style={{height:7,borderRadius:999,background:"#E2E8F0",overflow:"hidden"}}><div style={{width:`${Math.min(100,Math.max(0,r.percentage))}%`,height:"100%",borderRadius:999,background:"linear-gradient(90deg,#635BDF,#8B5CF6)"}}/></div></div>}{r.remarks&&<div style={{marginTop:11,padding:10,borderRadius:11,background:"#F8FAFC",fontSize:12,color:C.sub}}>{r.remarks}</div>}</Card>})}</div>}

export function PTTests({child}){const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{let live=true;(async()=>{setLoading(true);setError("");try{if(!child?.id){setRows([]);return}const{data:links,error:linkError}=await supabase.from("batch_students").select("batch_id").eq("student_id",String(child.id)).eq("status","active").is("left_at",null);if(linkError)throw linkError;const batchIds=[...new Set((links||[]).map(x=>String(x.batch_id)).filter(Boolean))];if(!batchIds.length){setRows([]);return}const{data,error:e}=await supabase.from("tests").select("id,title,description,subject,test_date,total_marks,status,batch_id").in("batch_id",batchIds).order("test_date",{ascending:true});if(e)throw e;if(live)setRows(data||[])}catch(e){if(live){setError(e instanceof Error?e.message:"Unable to load tests.");setRows([])}}finally{if(live)setLoading(false)}})();return()=>{live=false}},[child?.id]);return <div>{error&&<Card style={{padding:14,color:"#B91C1C",background:"#FEF2F2",marginBottom:10}}>{error}</Card>}<Sec title="Scheduled Tests 🧪"/>{loading?<Card style={{padding:20,color:C.sub}}>Loading tests…</Card>:!rows.length?<Card style={{padding:20,color:C.sub}}>No scheduled tests found.</Card>:rows.map(t=><Card key={t.id} style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><div style={{fontWeight:800}}>{t.title}</div><div style={{fontSize:12,color:C.sub,marginTop:3}}>{t.subject||"—"} · {t.test_date||"—"}</div>{t.description&&<div style={{fontSize:12,color:C.sub,marginTop:6}}>{t.description}</div>}</div><div style={{fontWeight:900,color:C.accent,whiteSpace:"nowrap"}}>{t.total_marks??"—"} marks</div></div></Card>)}</div>}

export function ParentApp({user,onLogout}){const[showNotif,setShowNotif]=useState(false),[tab,setTab]=useState("home"),{child,loading,error}=useParentChild(user),tabs=[{key:"home",icon:"🏠",label:"Home"},{key:"tests",icon:"🧪",label:"Tests"},{key:"results",icon:"📊",label:"Results"},{key:"attendance",icon:"✅",label:"Attend."},{key:"homework",icon:"📝",label:"HW"},{key:"news",icon:"📢",label:"News"}];const content=loading?<Card style={{padding:26,textAlign:"center",color:C.sub}}>Loading student profile…</Card>:error?<Card style={{padding:14,color:"#B91C1C",background:"#FEF2F2"}}>{error}</Card>:!child?<Card style={{padding:26,textAlign:"center",color:C.sub}}>No linked student profile found for this parent account.</Card>:tab==="home"?<PTHome child={child}/>:tab==="tests"?<PTTests child={child}/>:tab==="results"?<PTResults child={child}/>:tab==="attendance"?<PTAttendance child={child}/>:tab==="news"?<div><Sec title="Announcements 📢"/>{lsG("announcements").map(a=><Card key={a.id} style={{marginBottom:10}}><div style={{fontWeight:800}}>{a.title}</div><div style={{fontSize:12,color:C.sub}}>{a.desc}</div></Card>)}</div>:<div><Sec title="Homework 📝"/>{(child?lsG("homework").filter(h=>h.cls===child.cls&&h.sec===child.sec):[]).map(h=><Card key={h.id} style={{marginBottom:10}}><Badge label={h.subject}/><div style={{fontWeight:700,marginTop:7}}>{h.desc}</div><div style={{fontSize:11,color:C.sub}}>Due: {h.due}</div>{h.pdfName&&<PDFViewer pdfData={h.pdfData} pdfName={h.pdfName}/>}</Card>)}</div>;return <><Shell header={<AppBar name={user.name} role="parent" userId={user.id} onLogout={onLogout} onNotif={()=>setShowNotif(true)}/>} tabs={tabs} activeTab={tab} setTab={setTab}>{content}</Shell>{showNotif&&<ParentNotifications onClose={()=>setShowNotif(false)}/>}</>}
