import React,{useEffect,useState}from"react";
import {C,today,gdb,formatTimeRange12}from"@/lg/data";
import {Card,Sec}from"@/lg/ui";
import {StudentAnnouncements}from"@/lg/StudentAnnouncements";
const text=v=>v==null?"":String(v);
const dayOrder={Monday:1,Tuesday:2,Wednesday:3,Thursday:4,Friday:5,Saturday:6,Sunday:7};
const dayShort={Monday:"M",Tuesday:"T",Wednesday:"W",Thursday:"T",Friday:"F",Saturday:"S",Sunday:"Su"};
const loadSlots=async student=>{const batch=text(student?.batch_id||student?.batchId),c=text(student?.cls),s=text(student?.sec);const all=await gdb("timetable");return (Array.isArray(all)?all:[]).filter(r=>batch&&r.batchId?String(r.batchId)===batch:String(r.cls||"")===c&&String(r.sec||"")===s)};
export function STHome({student}){const[rows,setRows]=useState([]),[error,setError]=useState(""),[showAnnouncements,setShowAnnouncements]=useState(false);useEffect(()=>{let live=true;(async()=>{try{const d=await loadSlots(student);if(live){setRows(d);setError("")}}catch(e){if(live)setError(e instanceof Error?e.message:"Unable to load timetable.")}})();return()=>{live=false}},[student]);const todayRows=rows.filter(r=>r.day===today());const code=[...new Set(rows.map(r=>r.day).filter(Boolean))].sort((a,b)=>(dayOrder[a]||99)-(dayOrder[b]||99)).map(d=>dayShort[d]||d[0]).join("");return <div>{error&&<Card style={{color:C.red,marginBottom:10}}>{error}</Card>}<Card style={{marginBottom:16,background:"linear-gradient(135deg,#5B4FE8,#7B6FF5)",border:0,color:"#fff"}}><div style={{fontSize:20,fontWeight:900}}>{student?.name||"Student"}</div><div style={{fontSize:12,opacity:.8}}>Class {student?.cls||"—"}{student?.sec?`-${student.sec}`:""} · {student?.sid||""}</div><div style={{display:"flex",gap:10,marginTop:13}}><div style={{background:"rgba(255,255,255,.16)",borderRadius:10,padding:"8px 12px"}}><b>{todayRows.length}</b><div style={{fontSize:10,opacity:.75}}>Today</div></div><div style={{background:"rgba(255,255,255,.16)",borderRadius:10,padding:"8px 12px"}}><b>{code||"—"}</b><div style={{fontSize:10,opacity:.75}}>Schedule</div></div></div></Card><Card style={{marginBottom:16,cursor:"pointer"}} onClick={()=>setShowAnnouncements(v=>!v)}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><div style={{fontWeight:900}}>📢 Announcements & News</div><div style={{fontSize:11,color:C.sub,marginTop:3}}>View institute updates for students</div></div><span style={{color:C.accent,fontWeight:800}}>{showAnnouncements?"Close":"Open →"}</span></div></Card>{showAnnouncements?<StudentAnnouncements student={student}/>:<><Sec title={`Today – ${today()} 📖`}/>{todayRows.length?todayRows.map(r=><Card key={r.id} style={{marginBottom:8}}><div style={{fontWeight:800}}>{r.subject||"Class"}</div><div style={{fontSize:11,color:C.sub}}>{r.start_time!=null&&r.end_time!=null?formatTimeRange12(r.start_time,r.end_time):r.slot||"—"}{r.teacherName?` · ${r.teacherName}`:""}</div></Card>):<Card style={{padding:24,textAlign:"center",color:C.sub}}>No classes today.</Card>}</>}</div>}
export function STTimetable({student}){const[rows,setRows]=useState([]),[error,setError]=useState("");useEffect(()=>{let live=true;(async()=>{try{const d=await loadSlots(student);if(live){setRows(d);setError("")}}catch(e){if(live)setError(e instanceof Error?e.message:"Unable to load timetable.")}})();return()=>{live=false}},[student]);const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];const todayName=today();const orderedDays=[todayName,...days.filter(d=>d!==todayName)];return <div>{error&&<Card style={{color:C.red,marginBottom:10}}>{error}</Card>}<Sec title="My Timetable 📅"/>{orderedDays.map(day=>{const list=rows.filter(r=>r.day===day);return <div key={day} style={{marginBottom:13}}><div style={{fontSize:12,fontWeight:900,color:day===todayName?C.accent:C.sub,marginBottom:6}}>{day}{day===todayName?" · Today":""}</div>{list.length?list.map(r=><Card key={r.id} style={{marginBottom:7,display:"flex",justifyContent:"space-between",gap:10}}><div><div style={{fontWeight:800}}>{r.subject||"Class"}</div><div style={{fontSize:11,color:C.sub}}>{r.teacherName||""}</div></div><div style={{fontSize:11,color:C.sub}}>{r.start_time!=null&&r.end_time!=null?formatTimeRange12(r.start_time,r.end_time):r.slot||"—"}</div></Card>):<div style={{fontSize:11,color:C.sub,paddingLeft:8}}>No classes</div>}</div>})}</div>}
export {StudentAppFixed as StudentApp} from"@/lg/StudentAppFixed";
export {STAttendance,STFees} from"@/lg/studentPortal";
