import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lg/supabase";
import { C, formatTimeRange12 } from "@/lg/data";
import { Badge, Card, Sec } from "@/lg/ui";

const sid = (student) => String(student?.id ?? "");
const batchIds = (student) => [...new Set([...(Array.isArray(student?.batchIds) ? student.batchIds : []), student?.batch_id, student?.batchId].filter(Boolean).map(String))];
const ErrorCard = ({ message }) => message ? <Card style={{ color: C.red, background: "#FEF2F2", marginBottom: 12 }}>{message}</Card> : null;

export function STAttendance({ student }) {
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const studentId = String(student?.id ?? "");
  useEffect(() => { let live = true; if (!studentId) { setRows([]); setLoading(false); return () => { live = false; }; } setLoading(true); (async () => { try { const { data, error: e } = await supabase.from("attendance").select("id,sid,date,status,by,created_at").eq("sid", studentId).order("date", { ascending: false }); if (e) throw e; if (live) { setRows(data || []); setError(""); } } catch (e) { if (live) setError(e instanceof Error ? e.message : "Unable to load attendance."); } finally { if (live) setLoading(false); } })(); return () => { live = false; }; }, [studentId]);
  const rate = useMemo(() => { if (!rows.length) return null; let present = 0; for (const row of rows) if (String(row.status).toLowerCase() === "present") present++; return Math.round(present / rows.length * 100); }, [rows]);
  return <div><ErrorCard message={error} /><Card style={{ textAlign: "center", padding: 24, marginBottom: 16 }}><div style={{ color: C.sub, fontSize: 12 }}>Overall Attendance</div><div style={{ fontSize: 48, fontWeight: 900 }}>{rate == null ? "—" : `${rate}%`}</div></Card><Sec title="Attendance Log 📋" />{loading ? <Card>Loading attendance…</Card> : rows.length ? rows.map(r => <Card key={r.id} style={{ marginBottom: 8, display: "flex", justifyContent: "space-between" }}><span>{r.date || "—"}</span><Badge label={r.status || "unknown"} /></Card>) : <Card>No attendance records have been saved for this student yet.</Card>}</div>;
}

export function STFees({ student }) { const [rows,setRows]=useState([]); const studentId = String(student?.id ?? ""); useEffect(()=>{let live=true;if(!studentId){setRows([]);return()=>{live=false}};(async()=>{const{data}=await supabase.from("fees").select("id,sid,desc,amount,due,status,paidon").eq("sid",studentId).order("due");if(live)setRows(data||[])})();return()=>{live=false}},[studentId]); return <div><Sec title="Fees 💰"/>{rows.length?rows.map(r=><Card key={r.id} style={{marginBottom:8,display:"flex",justifyContent:"space-between"}}><span>{r.desc||"Fee"}</span><span>₹{Number(r.amount||0).toLocaleString("en-IN")} · {r.status||"pending"}</span></Card>):<Card>No fee records found.</Card>}</div>; }
export function STAnnouncements({ student }) { const[rows,setRows]=useState([]); useEffect(()=>{let live=true;(async()=>{const{data}=await supabase.from("announcements").select("id,title,desc,date,target,created_at").in("target",["all","everyone","student","students"]).order("created_at",{ascending:false});if(live)setRows(data||[])})();return()=>{live=false}},[]); return <div><Sec title="Announcements 📢"/>{rows.length?rows.map(r=><Card key={r.id} style={{marginBottom:8}}><b>{r.title}</b><div style={{fontSize:12,color:C.sub}}>{r.desc}</div></Card>):<Card>No announcements.</Card>}</div>; }
export function STHome({ student }) { return <div><Card style={{marginBottom:16}}><h2 style={{margin:"0 0 4px"}}>{student?.name||"Student"}</h2><div style={{fontSize:12,color:C.sub}}>Class {student?.cls||"—"}-{student?.sec||"—"} · {student?.sid||""}</div></Card><STAttendance student={student}/></div>; }
export function STTimetable({ student }) { const[rows,setRows]=useState([]); const ids = useMemo(() => batchIds(student), [student?.batchIds, student?.batch_id, student?.batchId]); const idsKey = ids.join(","); useEffect(()=>{let live=true;if(!ids.length){setRows([]);return()=>{live=false}};(async()=>{const{data}=await supabase.from("timetable_entries").select("id,day_of_week,start_time,end_time,subject_name,batch_id").in("batch_id",ids).eq("status","active");if(live)setRows(data||[])})();return()=>{live=false}},[idsKey]); return <div><Sec title="My Timetable 📅"/>{rows.length?rows.map(r=><Card key={r.id} style={{marginBottom:8}}><b>Day {r.day_of_week} · {formatTimeRange12(r.start_time,r.end_time)}</b><div style={{fontSize:12,color:C.sub}}>{r.subject_name||"Class"}</div></Card>):<Card>No timetable entries for your active batches.</Card>}</div>; }
