import React,{lazy,Suspense,useEffect,useState}from"react";
import {C}from"@/lg/data";
import {supabase}from"@/lg/supabase";
import {Card,Shell,AppBar}from"@/lg/ui";
import {STHome,STTimetable}from"@/lg/student";
import {getCurrentInstituteContext}from"@/lg/tenant";

const StudentHomework = lazy(() => import("@/lg/StudentSecondaryPages").then(m => ({ default: m.Homework })));
const StudentMaterials = lazy(() => import("@/lg/StudentSecondaryPages").then(m => ({ default: m.STMaterials })));
const STExams = lazy(() => import("@/lg/studentResults").then(m => ({ default: m.STExams })));
const STResults = lazy(() => import("@/lg/studentResults").then(m => ({ default: m.STResults })));
const STAttendanceFixed = lazy(() => import("@/lg/studentAttendance").then(m => ({ default: m.STAttendanceFixed })));
const NotifPanel = lazy(() => import("@/lg/panels").then(m => ({ default: m.NotifPanel })));
export function StudentAppFixed({user,onLogout}){const[tab,setTab]=useState("home"),[showNotif,setShowNotif]=useState(false),[student,setStudent]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{let live=true;(async()=>{try{const context=await getCurrentInstituteContext();const instituteId=context.membership?.institute_id;if(!instituteId)throw new Error("An active institute workspace must be selected.");const[profileResult,batchResult]=await Promise.all([supabase.from("students").select("id,name,sid,cls,sec,parentname,parentphone,parent,enroll,status").eq("institute_id",instituteId).eq("id",user.ref).maybeSingle(),supabase.from("batch_students").select("batch_id,status,left_at,joined_at").eq("institute_id",instituteId).eq("student_id",user.ref).eq("status","active").is("left_at",null).order("joined_at",{ascending:false})]);if(profileResult.error)throw profileResult.error;if(batchResult.error)throw batchResult.error;if(!profileResult.data)throw new Error("Student profile could not be loaded");const batchIds=[...new Set((batchResult.data||[]).map(r=>r.batch_id).filter(Boolean).map(String))];if(live)setStudent({...profileResult.data,batchIds,batchId:batchIds[0]||""})}catch(e){if(live)setError(e.message)}finally{if(live)setLoading(false)}})();return()=>{live=false}},[user.ref]);const tabs=[{key:"home",icon:"🏠",label:"Home"},{key:"timetable",icon:"📅",label:"Schedule"},{key:"materials",icon:"📚",label:"Materials"},{key:"homework",icon:"📝",label:"HW"},{key:"exams",icon:"📋",label:"Exams"},{key:"results",icon:"🏆",label:"Results"},{key:"attendance",icon:"✅",label:"Attend."}];const content=loading?<Card style={{textAlign:"center",padding:30,color:C.sub}}>Loading your student profile…</Card>:error?<Card style={{color:C.red,marginTop:20}}>{error}</Card>:tab==="home"?<STHome student={student}/>:tab==="timetable"?<STTimetable student={student}/>:tab==="materials"?<StudentMaterials student={student}/>:tab==="homework"?<StudentHomework student={student}/>:tab==="exams"?<STExams student={student}/>:tab==="results"?<STResults student={student}/>:<STAttendanceFixed student={student}/>;return <><Shell header={<AppBar name={user.name} role="student" userId={user.id} onLogout={onLogout} onNotif={()=>setShowNotif(true)}/>} tabs={tabs} activeTab={tab} setTab={setTab}>{content}</Shell>{showNotif&&<Suspense fallback={null}><NotifPanel userId={user.id} onClose={()=>setShowNotif(false)}/>}</>}
