import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/lg/supabase";
import { C } from "@/lg/data";
import { Badge, Card, Sec } from "@/lg/ui";

const text = (v) => (v == null ? "" : String(v));
const studentId = (student) => text(student?.id);
const cls = (student) => text(student?.cls);
const sec = (student) => text(student?.sec);
const batchIds = (student) => [...new Set([...(Array.isArray(student?.batchIds) ? student.batchIds : []), student?.batch_id, student?.batchId].filter(Boolean).map(String))];

function ErrorCard({ message }) { return message ? <Card style={{ color: C.red, marginBottom: 12, background: "#FEF2F2" }}>{message}</Card> : null; }

export function STAttendance({ student }) {
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const id = studentId(student); if (!id) { setRows([]); return; } const { data, error: e } = await supabase.from("attendance").select("id,sid,date,status,by,created_at").eq("sid", id).order("date", { ascending: false }); if (e) throw e; setRows(data || []); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load attendance."); } finally { setLoading(false); } }, [student?.id]);
  useEffect(() => { void load(); }, [load]);
  const present = rows.filter(r => text(r.status).toLowerCase() === "present").length; const absent = rows.filter(r => text(r.status).toLowerCase() === "absent").length; const leave = rows.filter(r => text(r.status).toLowerCase() === "leave").length; const rate = rows.length ? Math.round((present / rows.length) * 100) : null;
  return <div><ErrorCard message={error} /><Card style={{ textAlign:"center", padding:24, marginBottom:16 }}><div style={{ fontSize:12, color:C.sub }}>Overall Attendance</div><div style={{ fontSize:48, fontWeight:900, color:rate == null ? C.sub : rate >= 75 ? C.green : C.red }}>{rate == null ? "—" : `${rate}%`}</div><div style={{ display:"flex", justifyContent:"center", gap:24, marginTop:12, fontSize:12 }}><span>✅ {present}</span><span>❌ {absent}</span><span>🟡 {leave}</span></div></Card><Sec title="Attendance Log 📋" />{loading ? <Card style={{padding:26,textAlign:"center",color:C.sub}}>Loading attendance…</Card> : rows.length ? rows.map(r => <Card key={r.id} style={{marginBottom:8,display:"flex",justifyContent:"space-between",alignItems:"center"}}><span>{r.date || "—"}</span><Badge label={r.status || "unknown"} /></Card>) : <Card style={{padding:26,textAlign:"center",color:C.sub}}>No attendance records have been saved for this student yet.</Card>}</div>;
}

export function STFees({ student }) { const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); useEffect(()=>{let live=true;(async()=>{try{const{data,error:e}=await supabase.from("fees").select("id,sid,desc,amount,due,status,paidon,created_at").eq("sid",text(student?.sid||student?.id)).order("due",{ascending:true});if(e)throw e;if(live)setRows(data||[])}catch(e){if(live)setError(e instanceof Error?e.message:"Unable to load fees.")}finally{if(live)setLoading(false)}})();return()=>{live=false}},[student?.sid,student?.id]);const total=rows.reduce((n,r)=>n+Number(r.amount||0),0),paid=rows.filter(r=>text(r.status).toLowerCase()==="paid").reduce((n,r)=>n+Number(r.amount||0),0);return <div><ErrorCard message={error}/><Card style={{marginBottom:16,background:"linear-gradient(135deg,#22C55E,#16A34A)",border:0,color:"#fff"}}><div style={{fontSize:12,opacity:.8}}>Outstanding Fees</div><div style={{fontSize:32,fontWeight:900}}>₹{(total-paid).toLocaleString("en-IN")}</div><div style={{fontSize:12,opacity:.85}}>Total ₹{total.toLocaleString("en-IN")} · Paid ₹{paid.toLocaleString("en-IN")}</div></Card><Sec title="Fee Details 💰"/>{loading?<Card style={{padding:26,textAlign:"center",color:C.sub}}>Loading fees…</Card>:rows.length?rows.map(r=><Card key={r.id} style={{marginBottom:9,display:"flex",justifyContent:"space-between",gap:12}}><div><div style={{fontWeight:800}}>{r.desc||"Fee"}</div><div style={{fontSize:11,color:C.sub}}>Due: {r.due||"—"}{r.paidon?` · Paid: ${r.paidon}`:""}</div></div><div style={{textAlign:"right"}}><div style={{fontWeight:900}}>₹{Number(r.amount||0).toLocaleString("en-IN")}</div><Badge label={r.status||"pending"}/></div></Card>):<Card style={{padding:26,textAlign:"center",color:C.sub}}>No fee records have been saved for this student.</Card>}</div> }

export function STAnnouncements({ student }) { const[rows,setRows]=useState([]);const[error,setError]=useState("");useEffect(()=>{let live=true;(async()=>{try{const ids=batchIds(student),targets=["all","everyone","student","students"];const{data,error:e}=await supabase.from("announcements").select("id,title,desc,date,target,created_at").in("target",targets).order("created_at",{ascending:false});if(e)throw e;const b=ids.length?await supabase.from("announcements").select("id,title,desc,date,target,created_at").in("target",ids.map(id=>`batch:${id}`)).order("created_at",{ascending:false}):{data:[],error:null};if(b.error)throw b.error;const merged=[...(data||[]),...(b.data||[])].filter((r,i,a)=>a.findIndex(x=>String(x.id)===String(r.id))===i);if(live)setRows(merged)}catch(e){if(live)setError(e instanceof Error?e.message:"Unable to load announcements.")}})();return()=>{live=false}},[student]);return <div><ErrorCard message={error}/><Sec title="Announcements 📢"/>{rows.length?rows.map(r=><Card key={r.id} style={{marginBottom:9}}><div style={{fontWeight:800}}>{r.title}</div><div style={{fontSize:12,color:C.sub,marginTop:4}}>{r.desc}</div><div style={{fontSize:10,color:C.sub,marginTop:6}}>{r.date||r.created_at||""}</div></Card>):<Card style={{padding:26,textAlign:"center",color:C.sub}}>No announcements.</Card>}</div> }

export function STHome({student}){return <div><Card style={{marginBottom:16,background:"linear-gradient(135deg,#5B4FE8,#7B6FF5)",border:0,color:"#fff"}}><div style={{fontSize:20,fontWeight:900}}>{student?.name||"Student"}</div><div style={{fontSize:12,opacity:.8}}>Class {student?.cls||"—"}{student?.sec?`-${student.sec}`:""} · {student?.sid||""}</div></Card><STAttendance student={student}/><div style={{marginTop:16}}><STAnnouncements student={student}/></div></div>}

export function STTimetable({student}){const[rows,setRows]=useState([]),[error,setError]=useState("");useEffect(()=>{let live=true;(async()=>{try{const{data,error:e}=await supabase.from("timetable_entries").select("id,day_of_week,start_time,end_time,subject_name,teacher_id,batch_id").eq("status","active");if(e)throw e;const allowed=new Set(batchIds(student));if(live)setRows((data||[]).filter(r=>allowed.has(String(r.batch_id)))}catch(e){if(live)setError(e instanceof Error?e.message:"Unable to load timetable.")}})();return()=>{live=false}},[student]);return <div><ErrorCard message={error}/><Sec title="My Timetable 📅"/>{rows.length?rows.map(r=><Card key={r.id} style={{marginBottom:8}}><div style={{fontWeight:800}}>Day {r.day_of_week} · {String(r.start_time||"").slice(0,5)}–{String(r.end_time||"").slice(0,5)}</div><div style={{fontSize:12,color:C.sub,marginTop:3}}>{r.subject_name||"Class"}</div></Card>):<Card style={{padding:26,textAlign:"center",color:C.sub}}>No timetable entries for your active batches.</Card>}</div>}
